# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 807d02fb65c0f58cf6ac48556f45b344f2ad1d4818f91d02aaf722d529b8f64095b55ae54afafc49f52828a4ef8ada6b3660fcba9517dc76983630785bf83bae

test:
  secret_key_base: 759671154bf79350900a81698433760b86fff607ef70dc110ad3d1b222403dda20ddf7c27674ab93b9e3760f7d633aad9f19341bc5b4d6d21e9a6c7d1e3e4e78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
